FROM lego-service-base:latest
COPY requirements.txt .
RUN pip3 install -r requirements.txt
COPY src/ src
COPY templates/ templates
EXPOSE 8004
CMD ["uvicorn", "src.index:app", "--host", "0.0.0.0", "--port", "8004"]